### ISSUE TITLE
bake_action() missing 1 required keyword-only argument: 'frames'

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#131]
**OS:**

Linux

**Godot version:**

3.1.alpha.custom_build.29f2571

**Blender version:**

Blender 2.79 (sub 6)

**Issue description:**

Tried to export a rigged mesh with several animations, and got:

```
[INFO]: Exporting scene: Scene
[INFO]: Exporting 2 objects
[INFO]: Exporting Blender Object: Armature
Traceback (most recent call last):
  File "/home/rcorre/code/dust/./blender-export.py", line 11, in <module>
    io_scene_godot.export(outfile, {})
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/__init__.py", line 238, in export
    export_godot.save(FakeOp(), bpy.context, filename, **default_settings)
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/export_godot.py", line 218, in save
    exp.export()
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/export_godot.py", line 185, in export
    self.export_scene()
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/export_godot.py", line 173, in export_scene
    self.export_node(obj, root_gd_node)
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/export_godot.py", line 119, in export_node
    "transform"
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/converters/animation.py", line 810, in export_animation_data
    export_active_action(active_action)
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/converters/animation.py", line 787, in export_active_action
    action_active_to_export = action_baker(active_action)
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/converters/animation.py", line 758, in action_baker
    blender_object, action_to_bake, "POSE", False
  File "/usr/share/blender/2.79/scripts/addons/io_scene_godot/converters/animation.py", line 402, in bake_constraint_to_action
    do_visual_keying=True,
TypeError: bake_action() missing 1 required keyword-only argument: 'frames'
```

**Minimal reproduction project:**

[example.zip](https://github.com/godotengine/godot-blender-exporter/files/2729077/example.zip)

**Comment by rcorre** [comment]
The failed export also changes the name of the current animation in the dope sheet to `$name--being-baking`.

**Comment by rcorre** [comment]
Seems like the `bake_action` API changed:

2.80: https://docs.blender.org/api/master/bpy_extras.anim_utils.html?highlight=bake_action#bpy_extras.anim_utils.bake_action

2.79: https://docs.blender.org/api/2.79b/bpy_extras.anim_utils.html?highlight=bake_action#bpy_extras.anim_utils.bake_action

I'm confused why I seem to have the 2.80 API, even though I'm on 2.79.

**Comment by rcorre** [comment]
> I'm confused why I seem to have the 2.80 API, even though I'm on 2.79.

Turns out the [arch PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/blender) doesn't always use a tagged commit. I think I have a build with the 2.80 API that is still tagged as 2.79, so I've updated the patch to use the new API only with 2.80+.

I could have sworn I had the tests passing when I submitted this, but now I ran into a slew of new issues, some of which appear to be that `bake_action` is [broken upstream](https://developer.blender.org/D4172).

With both blender and the exporter patched, I got it running again, but my exported animation only seems to have one frame :/

**Comment by Jason0214** [comment]
>I could have sworn I had the tests passing when I submitted this, but now I ran into a slew of new >issues, some of which appear to be that bake_action is broken upstream.

Yeah, you are correct...   I noticed it when I update this exporter to fit into blender2.8 too. Then I turned to the another function `bake_action_objects` (see [godot-blender-exporter blender2.8](https://github.com/godotengine/godot-blender-exporter/blob/blender2.8/io_scene_godot/converters/animation/constraint_baking.py#L58) ), it is fine in blender2.8 API
