### ISSUE TITLE
TypeError: Object.to_mesh(): required parameter "depsgraph" not specified

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot-blender-exporter#218]
**OS:**
Manjaro Linux 18.3

**Blender version:**
2.8-beta / 5ac7675f4

**Issue description:**
After updating the exporter to f0bf680190b, I'm no longer able to export my model in Blender 2.8 as it fails with the following message:

```
Traceback (most recent call last):
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/__init__.py", line 205, in execute
    return export_godot.save(self, context, **keywords)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 292, in save
    exp.export()
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 249, in export
    self.export_scene()
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 205, in export_scene
    self.export_object(obj, root_gd_node)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 153, in export_object
    self.export_object(child, exported_node)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 125, in export_object
    parent_gd_node)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 45, in export_mesh_node
    mesh_id = mesh_exporter.export_mesh(escn_file, export_settings)
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 165, in export_mesh
    export_settings,
  File "/home/fender/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 181, in make_arrays
    mesh = self.object.to_mesh()
TypeError: Object.to_mesh(): required parameter "depsgraph" not specified
```

**Comment by Nathan173AB** [comment]
Confirmed. I'm experiencing the same issue on Ubuntu 18.04.

```
Traceback (most recent call last):
  File "/home/nathan173ab/.config/blender/2.80/scripts/addons/io_scene_godot/__init__.py", line 205, in execute
    return export_godot.save(self, context, **keywords)
  File "/home/nathan173ab/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 292, in save
    exp.export()
  File "/home/nathan173ab/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 249, in export
    self.export_scene()
  File "/home/nathan173ab/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 205, in export_scene
    self.export_object(obj, root_gd_node)
  File "/home/nathan173ab/.config/blender/2.80/scripts/addons/io_scene_godot/export_godot.py", line 125, in export_object
    parent_gd_node)
  File "/home/nathan173ab/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 45, in export_mesh_node
    mesh_id = mesh_exporter.export_mesh(escn_file, export_settings)
  File "/home/nathan173ab/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 165, in export_mesh
    export_settings,
  File "/home/nathan173ab/.config/blender/2.80/scripts/addons/io_scene_godot/converters/mesh.py", line 181, in make_arrays
    mesh = self.object.to_mesh()
TypeError: Object.to_mesh(): required parameter "depsgraph" not specified

```
location: <unknown location>:-1

**Comment by Jason0214** [comment]
Should be fixed on the current HEAD of `blender2.8`
