### ISSUE TITLE
Syntax error preventing this plugin from activating

### ISSUE THREAD

**Issue by Garrom** [godotengine/godot-blender-exporter#270]
**OS:**
Linux Mint Debian Edition( Basically Debian with Mint UI )

**Godot version:**
3.1.1 Stable Official

**Blender version:**
2.79

**Issue description:**
After I put files to plugin folder, it becomes visible in list of installed add-ons. However attempt to active plugin results in error below. Syntax error maybe ?

```
bpy.data.window_managers["WinMan"].addon_search = "godot"
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/scripts/addons/io_scene_godot/__init__.py", line 49
    filter_glob: StringProperty(default="*.escn", options={"HIDDEN"})
               ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/scripts/addons/io_scene_godot/__init__.py", line 49
    filter_glob: StringProperty(default="*.escn", options={"HIDDEN"})
               ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/scripts/addons/io_scene_godot/__init__.py", line 49
    filter_glob: StringProperty(default="*.escn", options={"HIDDEN"})
               ^
SyntaxError: invalid syntax
```
And yes, I attempted to activate plugin three times

**Comment by akien-mga** [comment]
Are you using the version from the `blender2.79` branch? https://github.com/godotengine/godot-blender-exporter/tree/blender2.79

**Comment by Garrom** [comment]
> Are you using the version from the `blender2.79` branch? https://github.com/godotengine/godot-blender-exporter/tree/blender2.79

No, I had no idea there are separated versions so I just pulled master. Thanks for help !
