### ISSUE TITLE
API change on Blender 2.81 breaks exporting process with incorrect arguments

### ISSUE THREAD

**Issue by JacobTheHeartless** [godotengine/godot-blender-exporter#306]
**OS:**
Linux. LMDE with XFCE

**Godot version:**
3.1.1 Official build

**Blender version:**
2.81

**Issue description:**
In attempt to export rigged and animated model in picture to subfolder on my project, I received error
![Snímek obrazovky_2019-12-26_06-15-11](https://user-images.githubusercontent.com/24418090/71459947-0d57c180-27aa-11ea-960b-b0bd8d420138.png)

Error I received is :
```
bpy.context.object.hide_viewport = True
bpy.context.object.hide_viewport = False
bpy.context.space_data.system_bookmarks_active = 0
bpy.data.window_managers["WinMan"].(null) = 'NONE'
bpy.data.window_managers["WinMan"].(null) = {'GEOMETRY'}
bpy.data.window_managers["WinMan"].(null) = {'ARMATURE', 'GEOMETRY'}
bpy.data.window_managers["WinMan"].(null) = False
bpy.data.window_managers["WinMan"].(null) = False
bpy.data.window_managers["WinMan"].(null) = False
bpy.data.window_managers["WinMan"].(null) = False
bpy.data.window_managers["WinMan"].(null) = "Spaceship"
bpy.ops.wm.operator_preset_add(name="spaceship", operator="EXPORT_GODOT_OT_escn")
Traceback (most recent call last):
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/__init__.py", line 198, in execute
    return export_godot.save(self, context, **keywords)
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/export_godot.py", line 318, in save
    exp.export()
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/export_godot.py", line 267, in export
    self.export_scene()
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/export_godot.py", line 211, in export_scene
    self.export_object(obj, root_gd_node)
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/export_godot.py", line 153, in export_object
    self.export_object(child, exported_node)
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/export_godot.py", line 123, in export_object
    parent_gd_node)
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/converters/mesh.py", line 45, in export_mesh_node
    mesh_id = mesh_exporter.export_mesh(escn_file, export_settings)
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/converters/mesh.py", line 165, in export_mesh
    mesh = mesh_converter.to_mesh()
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/converters/utils.py", line 139, in to_mesh
    triangulate_mesh(mesh)
  File "/home/jacob/.config/blender/2.81/scripts/addons/io_scene_godot/converters/utils.py", line 43, in triangulate_mesh
    mesh.update(calc_loop_triangles=True)
TypeError: Mesh.update(): was called with invalid keyword argument(s) (calc_loop_triangles), expected (calc_edges, calc_edges_loose)
 
location: <unknown location>:-1
```
Seems like API changed from 2.80 to 2.81 because Mesh.update() except different arguments

**Comment by JacobTheHeartless** [comment]
I'm sorry I'm idiot. Apparently 2.80 branch is **only** for 2.80. Looks like master branch works good under 2.81
