### ISSUE TITLE
'Vector' object has no attribute 'get_translation' when exporting animation with camera parented to bone

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot-blender-exporter#343]
**OS:**

Linux.

**Godot version:**

3.2.1.stable.custom_build.f0a489cf4

That's 3.2.1 with patches for the [quick resource selector](https://github.com/godotengine/godot/pull/37228) and [language server](https://github.com/godotengine/godot/pull/35864).

**Blender version:**

```
Blender 2.82 (sub 7)
	build date: 2020-05-13
	build time: 23:06:57
	build commit date: 2020-03-12
	build commit time: 05:06
	build hash: 375c7dc4caf4
```

**Issue description:**

1. Parented a camera to a bone on a Rigify-generated rig with animations
2. Exported:

```
Traceback (most recent call last):
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/__init__.py", line 215, in execute
    return export_godot.save(self, context, **keywords)
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/export_godot.py", line 318, in save
    exp.export()
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/export_godot.py", line 270, in export
    out_file.write(self.escn_file.to_string())
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/structures.py", line 99, in to_string
    '\n\n'.join(e.to_string() for e in self.internal_resources),
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/structures.py", line 99, in <genexpr>
    '\n\n'.join(e.to_string() for e in self.internal_resources),
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/structures.py", line 145, in to_string
    body = self.generate_body_string()
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/structures.py", line 138, in generate_body_string
    val = to_string(val)
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/structures.py", line 467, in to_string
    val = val.to_string()
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/converters/animation/serializer.py", line 172, in to_string
    return self.convert_to_keys_object().to_string()
  File "/home/rcorre/.config/blender/2.82/scripts/addons/io_scene_godot/converters/animation/serializer.py", line 307, in convert_to_keys_object
    self.parent_trans_inverse @ trans_frame.get_translation())
AttributeError: 'Vector' object has no attribute 'get_translation'

location: <unknown location>:-1
```

**Minimal reproduction project:**

Sorry this isn't minimal yet:
[example.zip](https://github.com/godotengine/godot-blender-exporter/files/4678711/example.zip)

**Comment by rcorre** [comment]
Also happens with an `Empty` parented to a bone (I used to use this technique to create a `BoneAttachment` with no children)
