### ISSUE TITLE
Docker build fails on setuptools upgrade

### ISSUE THREAD

**Issue by timjklein36** [godotengine/godot-blender-exporter#395]
**OS:**
Ubuntu Linux 18.04.2

**Godot version:**
3.2.3 (Not relevant since this issue only relates to running the `docker build` command)

**Blender version:**
From `Dockerfile` (2.81 as of this writing on `master`)

**Docker version:**
20.10.4

**Issue description:**
The build step described in the `README.md`:

```shell
sudo docker build . -t godot_blender_exporter:latest
```

...fails with the following output:

```
Step 6/13 : RUN pip3 install --upgrade setuptools
 ---> Running in a71db98cd95c
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Minimal reproduction project:**
Simply checkout `master` and run the `docker build` command listed in the `README.md`.

**Comment by timjklein36** [comment]
It seems to be an issue with the Python version installed on `xenial` systems (`3.5`). When I tested it with installing `3.6` (via an added PPA) the build works.
